// Icons
export const icons = {
  back: require("../../assets/icons/back.png"),
  backFat: require("../../assets/icons/backFat.png"),
  forward: require("../../assets/icons/forward.png"),
  user: require("../../assets/icons/user.png"),
  email: require("../../assets/icons/email.png"),
  password: require("../../assets/icons/password.png"),
  home: require("../../assets/icons/home.png"),
  isHome: require("../../assets/icons/isHome.png"),
  offers: require("../../assets/icons/offers.png"),
  isOffers: require("../../assets/icons/isOffers.png"),
  news: require("../../assets/icons/news.png"),
  profile: require("../../assets/icons/profile.png"),
  isProfile: require("../../assets/icons/isProfile.png"),
  logo: require("../../assets/icons/logo_icon.png"),
  notification: require("../../assets/icons/notification.png"),
  search: require("../../assets/icons/search.png"),
  setting: require("../../assets/icons/setting.png"),
  amazon: require("../../assets/icons/amazon.png"),
  daily: require("../../assets/icons/daily.png"),
  like: require("../../assets/icons/like.png"),
  dislike: require("../../assets/icons/dislike.png"),
  time: require("../../assets/icons/time.png"),
  filter: require("../../assets/icons/filter.png"),
  share: require("../../assets/icons/share.png"),
  apple: require("../../assets/icons/apple.png"),
  google: require("../../assets/icons/google.png"),
  check: require("../../assets/icons/check.png"),
  asus: require("../../assets/icons/asus.png"),
  canon: require("../../assets/icons/canon.png"),
  dell: require("../../assets/icons/dell.png"),
  handm: require("../../assets/icons/handm.png"),
  hp: require("../../assets/icons/hp.png"),
  lego: require("../../assets/icons/lego.png"),
  nike: require("../../assets/icons/nike.png"),
  samsung: require("../../assets/icons/samsung.png"),
  zara: require("../../assets/icons/zara.png"),
  searchBold: require("../../assets/icons/searchBold.png"),
  isSetting: require("../../assets/icons/isSetting.png"),
  isNews: require("../../assets/icons/isNews.png"),
  checkRight: require("../../assets/icons/checkRight.png"),
  cancel: require("../../assets/icons/cancel.png"),
};

export const images = {
  loginImg: require("../../assets/images/login_img.png"),
  registerImg: require("../../assets/images/register_img.png"),
  forgotPwdImg: require("../../assets/images/forgotPwd_img.png"),
  logo: require("../../assets/images/logo.png"),
  profile: require("../../assets/images/profile.png"),
  desserts1: require("../../assets/images/desserts1.jpeg"),
  desserts2: require("../../assets/images/desserts2.jpeg"),
  desserts3: require("../../assets/images/desserts3.jpeg"),
  amazon: require("../../assets/images/amazon.png"),
  eBay: require("../../assets/images/eBay.png"),
  spotify: require("../../assets/images/spotify.png"),
  redbull: require("../../assets/images/redbull.png"),
  highlight1: require("../../assets/images/highlight1.png"),
  highlight2: require("../../assets/images/highlight2.png"),
  news: require("../../assets/images/news.png"),
  analytics: require("../../assets/images/analytics.png"),
  coupons: require("../../assets/images/coupons.png"),
  noNotification: require("../../assets/images/no-notification.png"),
  noInternet: require("../../assets/images/no-internet.png"),
};

export const gifs = {
  logo: require("../../assets/gif/reselling_logo.gif"),
};
